/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.CarritoDAO;
import entidad.Caja;
import entidad.Producto;
import entidad.Carrito;
import datos.ClienteDAO;
import datos.ListaDetalleCarrito;
import entidad.Cliente;
import java.awt.Color;
import entidad.DetalleCarrito;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import entidad.Validaciones;

public class DialogCarrito extends javax.swing.JDialog {
    DefaultTableModel modelo = new DefaultTableModel();
   
    private Producto productoSelec=null;
    private Caja cajaSelec = null;
    private ListaDetalleCarrito LDC = new ListaDetalleCarrito();
    Validaciones x = new Validaciones();
    
    /**
     * Creates new form DialogCarrito
     */
    public DialogCarrito() {
        super(FrmPrincipal.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void habilitar(){
        btnActualizar.setEnabled(true);
        btnSalir.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnConsultar.setEnabled(false);
    }
    
     
    private void desHabilitar(){
        btnActualizar.setEnabled(false);
        btnSalir.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }     
    
    private void limpiarEntradas(){
        txtIdCliente.setText("");
        txtDniCliente.setText("");
        txtNombreCliente.setText("");
        txtEmailCliente.setText("");
        txtPuntosAcumulados.setText("");
        txtIdCarrito.setText("");
        txtImporte.setText("");
        txtFechaH.setText("");
        txtMedioPago.setText("");
        txtPuntosGanados.setText("");
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        txtPrecioVenta.setText("");
        txtCantidadComprada.setText("");
        txtIdCaja.setText("");
        txtNroCaja.setText("");
        txtIdCarrito.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDniCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtPuntosAcumulados = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIdCarrito = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        txtFechaH = new javax.swing.JTextField();
        txtMedioPago = new javax.swing.JTextField();
        txtPuntosGanados = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCantidadComprada = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        btnSeleccionarProdcuto = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtIdCaja = new javax.swing.JTextField();
        txtNroCaja = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        btnSeleccionarCaja = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 102, 102));
        btnSalir.setText("X");
        btnSalir.setAutoscrolls(true);
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("ID CLIENTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("DNI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("EMAIL");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("PUNTOS ACUMULADOS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono cliente.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 90, -1));

        txtIdCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtIdCliente.setText("Ingrese ID CLIENTE");
        txtIdCliente.setBorder(null);
        txtIdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdClienteMousePressed(evt);
            }
        });
        jPanel1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 290, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 290, 20));

        txtDniCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtDniCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDniCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtDniCliente.setText("Ingrese DNI");
        txtDniCliente.setBorder(null);
        txtDniCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniClienteMousePressed(evt);
            }
        });
        jPanel1.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 290, 30));

        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreCliente.setText("Ingrese NOMBRE CLIENTE");
        txtNombreCliente.setBorder(null);
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreClienteMousePressed(evt);
            }
        });
        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 290, 30));

        txtEmailCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmailCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtEmailCliente.setText("Ingrese EMAIL");
        txtEmailCliente.setBorder(null);
        txtEmailCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailClienteMousePressed(evt);
            }
        });
        jPanel1.add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 290, 30));

        txtPuntosAcumulados.setBackground(new java.awt.Color(255, 255, 255));
        txtPuntosAcumulados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPuntosAcumulados.setForeground(new java.awt.Color(204, 204, 204));
        txtPuntosAcumulados.setText("Ingrese PUNTOS ACUMULADOS");
        txtPuntosAcumulados.setBorder(null);
        txtPuntosAcumulados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPuntosAcumuladosMousePressed(evt);
            }
        });
        jPanel1.add(txtPuntosAcumulados, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 290, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 290, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 290, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 290, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 290, 20));

        jPanel2.setBackground(new java.awt.Color(99, 164, 64));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, 580));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("CARRITO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("ID CARRITO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("IMPORTE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("FECHA/HORA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("MEDIO DE PAGO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("PUNTOS GANADOS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono carrito.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 110, 100));

        txtIdCarrito.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCarrito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdCarrito.setForeground(new java.awt.Color(204, 204, 204));
        txtIdCarrito.setText("Ingrese ID CARRITO");
        txtIdCarrito.setBorder(null);
        txtIdCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdCarritoMousePressed(evt);
            }
        });
        jPanel1.add(txtIdCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 30));

        txtImporte.setBackground(new java.awt.Color(255, 255, 255));
        txtImporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(204, 204, 204));
        txtImporte.setText("Ingrese IMPORTE");
        txtImporte.setBorder(null);
        txtImporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtImporteMousePressed(evt);
            }
        });
        jPanel1.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 290, 30));

        txtFechaH.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFechaH.setForeground(new java.awt.Color(204, 204, 204));
        txtFechaH.setText("Ingrese FECHA/HORA");
        txtFechaH.setBorder(null);
        txtFechaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaHMousePressed(evt);
            }
        });
        jPanel1.add(txtFechaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 290, 30));

        txtMedioPago.setBackground(new java.awt.Color(255, 255, 255));
        txtMedioPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMedioPago.setForeground(new java.awt.Color(204, 204, 204));
        txtMedioPago.setText("Ingrese MEDIO DE PAGO");
        txtMedioPago.setBorder(null);
        txtMedioPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMedioPagoMousePressed(evt);
            }
        });
        jPanel1.add(txtMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 290, 30));

        txtPuntosGanados.setBackground(new java.awt.Color(255, 255, 255));
        txtPuntosGanados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPuntosGanados.setForeground(new java.awt.Color(204, 204, 204));
        txtPuntosGanados.setText("Ingrese PUNTOS GANADOS");
        txtPuntosGanados.setBorder(null);
        txtPuntosGanados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPuntosGanadosMousePressed(evt);
            }
        });
        jPanel1.add(txtPuntosGanados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 290, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 290, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 290, 20));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 290, 20));

        jPanel3.setBackground(new java.awt.Color(0, 161, 233));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 580));

        jLabel15.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("PRODUCTOS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("ID PRODUCTO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("NOMBRE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("PRECIO VENTA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("CANTIDAD COMPRADA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Producto - icono.jpg"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 90, 90));

        txtIdProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtIdProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtIdProducto.setText("Ingrese ID PRODUCTO");
        txtIdProducto.setBorder(null);
        txtIdProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdProductoMousePressed(evt);
            }
        });
        jPanel1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 290, 30));

        txtNombreProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreProducto.setText("Ingrese NOMBRE PRODUCTO");
        txtNombreProducto.setBorder(null);
        txtNombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProductoMousePressed(evt);
            }
        });
        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 290, 30));

        txtPrecioVenta.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPrecioVenta.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecioVenta.setText("Ingrese PRECIO VENTA");
        txtPrecioVenta.setBorder(null);
        txtPrecioVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioVentaMousePressed(evt);
            }
        });
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 290, 30));

        txtCantidadComprada.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidadComprada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCantidadComprada.setForeground(new java.awt.Color(204, 204, 204));
        txtCantidadComprada.setText("Ingrese CANTIDAD COMPRADA");
        txtCantidadComprada.setBorder(null);
        txtCantidadComprada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCantidadCompradaMousePressed(evt);
            }
        });
        jPanel1.add(txtCantidadComprada, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 290, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 290, 20));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 290, 20));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 290, 20));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 290, 20));

        btnSeleccionarProdcuto.setBackground(new java.awt.Color(0, 161, 233));
        btnSeleccionarProdcuto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeleccionarProdcuto.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarProdcuto.setText("SELECCIONAR");
        btnSeleccionarProdcuto.setBorderPainted(false);
        btnSeleccionarProdcuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProdcutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarProdcuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 120, 40));

        btnAgregar.setBackground(new java.awt.Color(0, 161, 233));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorderPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 120, 40));

        btnEliminarProducto.setBackground(new java.awt.Color(0, 161, 233));
        btnEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("ELIMINAR");
        btnEliminarProducto.setBorderPainted(false);
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 120, 40));

        jPanel4.setBackground(new java.awt.Color(135, 224, 200));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, 580));

        jLabel21.setFont(new java.awt.Font("Myanmar Text", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("CAJA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, -1, -1));

        jLabel22.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("ID CAJA");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("N° CAJA");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cashier2_117800.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, 100, 100));

        txtIdCaja.setBackground(new java.awt.Color(255, 255, 255));
        txtIdCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIdCaja.setForeground(new java.awt.Color(204, 204, 204));
        txtIdCaja.setText("Ingrese ID CAJA");
        txtIdCaja.setBorder(null);
        txtIdCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdCajaMousePressed(evt);
            }
        });
        jPanel1.add(txtIdCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 290, 30));

        txtNroCaja.setBackground(new java.awt.Color(255, 255, 255));
        txtNroCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNroCaja.setForeground(new java.awt.Color(204, 204, 204));
        txtNroCaja.setText("Ingrese N° CAJA");
        txtNroCaja.setBorder(null);
        txtNroCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNroCajaMousePressed(evt);
            }
        });
        jPanel1.add(txtNroCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 290, 30));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 290, 20));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 290, 20));

        btnSeleccionarCaja.setBackground(new java.awt.Color(135, 224, 200));
        btnSeleccionarCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeleccionarCaja.setForeground(new java.awt.Color(51, 51, 51));
        btnSeleccionarCaja.setText("SELECCIONAR");
        btnSeleccionarCaja.setBorderPainted(false);
        btnSeleccionarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 420, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(8, 8, 11));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 120, 40));

        btnActualizar.setBackground(new java.awt.Color(8, 8, 11));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorderPainted(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 120, 40));

        btnConsultar.setBackground(new java.awt.Color(8, 8, 11));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(8, 8, 11));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 700, 120, 40));

        btnRestaurar.setBackground(new java.awt.Color(8, 8, 11));
        btnRestaurar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRestaurar.setText("RESTAURAR");
        btnRestaurar.setBorderPainted(false);
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 120, 40));

        jTable1.setBackground(new java.awt.Color(8, 8, 11));
        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 850, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
        btnSalir.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
        x.validarLetras(evt);
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyTyped
        x.validarLetras(evt);
    }//GEN-LAST:event_txtNombreProductoKeyTyped

    private void txtIdCarritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdCarritoMousePressed
        if(txtIdCarrito.getText().equals("Ingrese ID CARRITO")){
            txtIdCarrito.setText("");
            txtIdCarrito.setForeground(new Color(102,102,102));
        }   
        if(txtImporte.getText().isEmpty()){
            txtImporte.setText("Ingrese IMPORTE");
            txtImporte.setForeground(new Color(204,204,204));
        }
        if(txtFechaH.getText().isEmpty()){
            txtFechaH.setText("Ingrese FECHA/HORA");
            txtFechaH.setForeground(new Color(204,204,204));
        }
        if(txtMedioPago.getText().isEmpty()){
            txtMedioPago.setText("Ingrese MEDIO DE PAGO");
            txtMedioPago.setForeground(new Color(204,204,204));
        }
        if(txtPuntosGanados.getText().isEmpty()){
            txtPuntosGanados.setText("Ingrese PUNTOS GANADOS");
            txtPuntosGanados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtIdCarritoMousePressed

    private void txtImporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImporteMousePressed
        if(txtIdCarrito.getText().isEmpty()){
            txtIdCarrito.setText("Ingrese ID CARRITO");
            txtIdCarrito.setForeground(new Color(204,204,204));
        }
        if(txtImporte.getText().equals("Ingrese IMPORTE")){
            txtImporte.setText("");
            txtImporte.setForeground(new Color(102,102,102));
        }  
        if(txtFechaH.getText().isEmpty()){
            txtFechaH.setText("Ingrese FECHA/HORA");
            txtFechaH.setForeground(new Color(204,204,204));
        }
        if(txtMedioPago.getText().isEmpty()){
            txtMedioPago.setText("Ingrese MEDIO DE PAGO");
            txtMedioPago.setForeground(new Color(204,204,204));
        }
        if(txtPuntosGanados.getText().isEmpty()){
            txtPuntosGanados.setText("Ingrese PUNTOS GANADOS");
            txtPuntosGanados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtImporteMousePressed

    private void txtFechaHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaHMousePressed
        if(txtIdCarrito.getText().isEmpty()){
            txtIdCarrito.setText("Ingrese ID CARRITO");
            txtIdCarrito.setForeground(new Color(204,204,204));
        }
        if(txtImporte.getText().isEmpty()){
            txtImporte.setText("Ingrese IMPORTE");
            txtImporte.setForeground(new Color(204,204,204));
        }
        if(txtFechaH.getText().equals("Ingrese FECHA/HORA")){
            txtFechaH.setText("");
            txtFechaH.setForeground(new Color(102,102,102));
        }
        if(txtMedioPago.getText().isEmpty()){
            txtMedioPago.setText("Ingrese MEDIO DE PAGO");
            txtMedioPago.setForeground(new Color(204,204,204));
        }
        if(txtPuntosGanados.getText().isEmpty()){
            txtPuntosGanados.setText("Ingrese PUNTOS GANADOS");
            txtPuntosGanados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtFechaHMousePressed

    private void txtMedioPagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMedioPagoMousePressed
        if(txtIdCarrito.getText().isEmpty()){
            txtIdCarrito.setText("Ingrese ID CARRITO");
            txtIdCarrito.setForeground(new Color(204,204,204));
        }
        if(txtImporte.getText().isEmpty()){
            txtImporte.setText("Ingrese IMPORTE");
            txtImporte.setForeground(new Color(204,204,204));
        }
        if(txtFechaH.getText().isEmpty()){
            txtFechaH.setText("Ingrese FECHA/HORA");
            txtFechaH.setForeground(new Color(204,204,204));
        }
        if(txtMedioPago.getText().equals("Ingrese MEDIO DE PAGO")){
            txtMedioPago.setText("");
            txtMedioPago.setForeground(new Color(102,102,102));
        }  
        if(txtPuntosGanados.getText().isEmpty()){
            txtPuntosGanados.setText("Ingrese PUNTOS GANADOS");
            txtPuntosGanados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtMedioPagoMousePressed

    private void txtPuntosGanadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPuntosGanadosMousePressed
        if(txtIdCarrito.getText().isEmpty()){
            txtIdCarrito.setText("Ingrese ID CARRITO");
            txtIdCarrito.setForeground(new Color(204,204,204));
        }
        if(txtImporte.getText().isEmpty()){
            txtImporte.setText("Ingrese IMPORTE");
            txtImporte.setForeground(new Color(204,204,204));
        }
        if(txtFechaH.getText().isEmpty()){
            txtFechaH.setText("Ingrese FECHA/HORA");
            txtFechaH.setForeground(new Color(204,204,204));
        }
        if(txtMedioPago.getText().isEmpty()){
            txtMedioPago.setText("Ingrese MEDIO DE PAGO");
            txtMedioPago.setForeground(new Color(204,204,204));
        }
        if(txtPuntosGanados.getText().equals("Ingrese PUNTOS GANADOS")){
            txtPuntosGanados.setText("");
            txtPuntosGanados.setForeground(new Color(102,102,102));
        }  
    }//GEN-LAST:event_txtPuntosGanadosMousePressed

    private void txtIdClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdClienteMousePressed
        if(txtIdCliente.getText().equals("Ingrese ID CLIENTE")){
            txtIdCliente.setText("");
            txtIdCliente.setForeground(new Color(102,102,102));
        }   
        if(txtDniCliente.getText().isEmpty()){
            txtDniCliente.setText("Ingrese DNI");
            txtDniCliente.setForeground(new Color(204,204,204));
        }
       if(txtNombreCliente.getText().isEmpty()){
            txtNombreCliente.setText("Ingrese NOMBRE CLIENTE");
            txtNombreCliente.setForeground(new Color(204,204,204));
        }
        if(txtEmailCliente.getText().isEmpty()){
            txtEmailCliente.setText("Ingrese EMAIL CLIENTE");
            txtEmailCliente.setForeground(new Color(204,204,204));
        }
        if(txtPuntosAcumulados.getText().isEmpty()){
            txtPuntosAcumulados.setText("Ingrese PUNTOS ACUMULADOS");
            txtPuntosAcumulados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtIdClienteMousePressed

    private void txtDniClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniClienteMousePressed
        if(txtIdCliente.getText().isEmpty()){
            txtIdCliente.setText("Ingrese ID CLIENTE");
            txtIdCliente.setForeground(new Color(204,204,204));
        }
        if(txtDniCliente.getText().equals("Ingrese DNI")){
            txtDniCliente.setText("");
            txtDniCliente.setForeground(new Color(102,102,102));
        } 
        if(txtNombreCliente.getText().isEmpty()){
            txtNombreCliente.setText("Ingrese NOMBRE CLIENTE");
            txtNombreCliente.setForeground(new Color(204,204,204));
        }
        if(txtEmailCliente.getText().isEmpty()){
            txtEmailCliente.setText("Ingrese EMAIL CLIENTE");
            txtEmailCliente.setForeground(new Color(204,204,204));
        }
        if(txtPuntosAcumulados.getText().isEmpty()){
            txtPuntosAcumulados.setText("Ingrese PUNTOS ACUMULADOS");
            txtPuntosAcumulados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtDniClienteMousePressed

    private void txtNombreClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMousePressed
        if(txtIdCliente.getText().isEmpty()){
            txtIdCliente.setText("Ingrese ID CLIENTE");
            txtIdCliente.setForeground(new Color(204,204,204));
        }
        if(txtDniCliente.getText().isEmpty()){
            txtDniCliente.setText("Ingrese DNI");
            txtDniCliente.setForeground(new Color(204,204,204));
        }
        if(txtNombreCliente.getText().equals("Ingrese NOMBRE CLIENTE")){
            txtNombreCliente.setText("");
            txtNombreCliente.setForeground(new Color(102,102,102));
        } 
        if(txtEmailCliente.getText().isEmpty()){
            txtEmailCliente.setText("Ingrese EMAIL CLIENTE");
            txtEmailCliente.setForeground(new Color(204,204,204));
        }
        if(txtPuntosAcumulados.getText().isEmpty()){
            txtPuntosAcumulados.setText("Ingrese PUNTOS ACUMULADOS");
            txtPuntosAcumulados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNombreClienteMousePressed

    private void txtEmailClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailClienteMousePressed
        if(txtIdCliente.getText().isEmpty()){
            txtIdCliente.setText("Ingrese ID CLIENTE");
            txtIdCliente.setForeground(new Color(204,204,204));
        }
        if(txtDniCliente.getText().isEmpty()){
            txtDniCliente.setText("Ingrese DNI");
            txtDniCliente.setForeground(new Color(204,204,204));
        }
        if(txtNombreCliente.getText().isEmpty()){
            txtNombreCliente.setText("Ingrese NOMBRE CLIENTE");
            txtNombreCliente.setForeground(new Color(204,204,204));
        }
        if(txtEmailCliente.getText().equals("Ingrese EMAIL")){
            txtEmailCliente.setText("");
            txtEmailCliente.setForeground(new Color(102,102,102));
        } 
        if(txtPuntosAcumulados.getText().isEmpty()){
            txtPuntosAcumulados.setText("Ingrese PUNTOS ACUMULADOS");
            txtPuntosAcumulados.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtEmailClienteMousePressed

    private void txtPuntosAcumuladosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPuntosAcumuladosMousePressed
        if(txtIdCliente.getText().isEmpty()){
            txtIdCliente.setText("Ingrese ID CLIENTE");
            txtIdCliente.setForeground(new Color(204,204,204));
        }
        if(txtDniCliente.getText().isEmpty()){
            txtDniCliente.setText("Ingrese DNI");
            txtDniCliente.setForeground(new Color(204,204,204));
        }
        if(txtNombreCliente.getText().isEmpty()){
            txtNombreCliente.setText("Ingrese NOMBRE CLIENTE");
            txtNombreCliente.setForeground(new Color(204,204,204));
        }
        if(txtEmailCliente.getText().isEmpty()){
            txtEmailCliente.setText("Ingrese EMAIL CLIENTE");
            txtEmailCliente.setForeground(new Color(204,204,204));
        }
        if(txtPuntosAcumulados.getText().equals("Ingrese PUNTOS ACUMULADOS")){
            txtPuntosAcumulados.setText("");
            txtPuntosAcumulados.setForeground(new Color(102,102,102));
        } 
    }//GEN-LAST:event_txtPuntosAcumuladosMousePressed

    private void txtIdProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdProductoMousePressed
        if(txtIdProducto.getText().equals("Ingrese ID PRODUCTO")){
            txtIdProducto.setText("");
            txtIdProducto.setForeground(new Color(102,102,102));
        }   
        if(txtNombreProducto.getText().isEmpty()){
            txtNombreProducto.setText("Ingrese NOMBRE PRODUCTO");
            txtNombreProducto.setForeground(new Color(204,204,204));
        }
        if(txtPrecioVenta.getText().isEmpty()){
            txtPrecioVenta.setText("Ingrese PRECIO VENTA");
            txtPrecioVenta.setForeground(new Color(204,204,204));
        }
        if(txtCantidadComprada.getText().isEmpty()){
            txtCantidadComprada.setText("Ingrese CANTIDAD COMPRADA");
            txtCantidadComprada.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtIdProductoMousePressed

    private void txtNombreProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProductoMousePressed
        if(txtIdProducto.getText().isEmpty()){
            txtIdProducto.setText("Ingrese ID PRODUCTO");
            txtIdProducto.setForeground(new Color(204,204,204));
        }
        if(txtNombreProducto.getText().equals("Ingrese NOMBRE PRODUCTO")){
            txtNombreProducto.setText("");
            txtNombreProducto.setForeground(new Color(102,102,102));
        }
        if(txtPrecioVenta.getText().isEmpty()){
            txtPrecioVenta.setText("Ingrese PRECIO VENTA");
            txtPrecioVenta.setForeground(new Color(204,204,204));
        }
        if(txtCantidadComprada.getText().isEmpty()){
            txtCantidadComprada.setText("Ingrese CANTIDAD COMPRADA");
            txtCantidadComprada.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNombreProductoMousePressed

    private void txtPrecioVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioVentaMousePressed
        if(txtIdProducto.getText().isEmpty()){
            txtIdProducto.setText("Ingrese ID PRODUCTO");
            txtIdProducto.setForeground(new Color(204,204,204));
        }
        if(txtNombreProducto.getText().isEmpty()){
            txtNombreProducto.setText("Ingrese NOMBRE PRODUCTO");
            txtNombreProducto.setForeground(new Color(204,204,204));
        }
        if(txtPrecioVenta.getText().equals("Ingrese PRECIO VENTA")){
            txtPrecioVenta.setText("");
            txtPrecioVenta.setForeground(new Color(102,102,102));
        }
        if(txtCantidadComprada.getText().isEmpty()){
            txtCantidadComprada.setText("Ingrese CANTIDAD COMPRADA");
            txtCantidadComprada.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtPrecioVentaMousePressed

    private void txtCantidadCompradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadCompradaMousePressed
        if(txtIdProducto.getText().isEmpty()){
            txtIdProducto.setText("Ingrese ID PRODUCTO");
            txtIdProducto.setForeground(new Color(204,204,204));
        }
        if(txtNombreProducto.getText().isEmpty()){
            txtNombreProducto.setText("Ingrese NOMBRE PRODUCTO");
            txtNombreProducto.setForeground(new Color(204,204,204));
        }
        if(txtPrecioVenta.getText().isEmpty()){
            txtPrecioVenta.setText("Ingrese PRECIO VENTA");
            txtPrecioVenta.setForeground(new Color(204,204,204));
        }
        if(txtCantidadComprada.getText().equals("Ingrese CANTIDAD COMPRADA")){
            txtCantidadComprada.setText("");
            txtCantidadComprada.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtCantidadCompradaMousePressed

    private void txtIdCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdCajaMousePressed
        if(txtIdCaja.getText().equals("Ingrese ID CAJA")){
            txtIdCaja.setText("");
            txtIdCaja.setForeground(new Color(102,102,102));
        }
        if(txtNroCaja.getText().isEmpty()){
            txtNroCaja.setText("Ingrese N° CAJA");
            txtNroCaja.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtIdCajaMousePressed

    private void txtNroCajaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroCajaMousePressed
        if(txtIdCaja.getText().isEmpty()){
            txtIdCaja.setText("Ingrese ID CAJA");
            txtIdCaja.setForeground(new Color(204,204,204));
        }
        if(txtNroCaja.getText().equals("Ingrese N° CAJA")){
            txtNroCaja.setText("");
            txtNroCaja.setForeground(new Color(102,102,102));
        } 
    }//GEN-LAST:event_txtNroCajaMousePressed

    private void btnSeleccionarProdcutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProdcutoActionPerformed
        DialogBuscarProducto f = new DialogBuscarProducto();
        f.setVisible(true);
        productoSelec = f.productoSelec;
        
        txtIdProducto.setText(productoSelec.getIdProducto());
        txtNombreProducto.setText(productoSelec.getNombre());
        txtPrecioVenta.setText(String.valueOf(productoSelec.getPrecioVenta()));
    }//GEN-LAST:event_btnSeleccionarProdcutoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int cantidad = Integer.parseInt(txtCantidadComprada.getText());
        DetalleCarrito detalleCar= new DetalleCarrito(productoSelec,cantidad);
        LDC.add(detalleCar);
        LDC.mostrar(modelo);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnSeleccionarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCajaActionPerformed
        DialogBuscarCaja f = new DialogBuscarCaja();
        f.setVisible(true);
        cajaSelec = f.cajaSelec;
        
        txtIdCaja.setText(cajaSelec.getIdCaja());
        txtNroCaja.setText(String.valueOf(cajaSelec.getNumeroDeCaja()));
    }//GEN-LAST:event_btnSeleccionarCajaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idCliente = txtIdCliente.getText();
        String dni = txtDniCliente.getText();
        String nombre = txtNombreCliente.getText();
        String email = txtEmailCliente.getText();
        int puntosAcu = Integer.parseInt(txtPuntosAcumulados.getText());
        Cliente cliente= new Cliente(idCliente,dni,nombre,email,puntosAcu);
        
        String idCarrito = txtIdCarrito.getText();
        double importe = Double.parseDouble(txtImporte.getText());
        String fechaHora = txtFechaH.getText();
        String medioPago = txtMedioPago.getText();
        int puntosGana = Integer.parseInt(txtPuntosGanados.getText());
        Carrito carrito = new Carrito(idCarrito,importe,fechaHora,medioPago,puntosGana,cliente,cajaSelec,LDC);  
        try{
            ClienteDAO.getInstancia().agregar(cliente);
            CarritoDAO.getInstancia().agregar(carrito);
        }catch(SQLException cli){
            JOptionPane.showMessageDialog(null, cli.getMessage());
        }

        limpiarEntradas();
        desHabilitar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        /*try{
            String idcaja = txtIdCarrito.getText();
            int ndeCaja = Integer.parseInt(txtImporte.getText());

            Caja caja= new Caja(idcaja, ndeCaja, supermercadoSelec);

            CajaDAO.getInstancia().actualizar(caja);
            CajaDAO.getInstancia().mostrar(modelo);
            JOptionPane.showMessageDialog(null,"Modificado");
        } catch (SQLException su) {
            JOptionPane.showMessageDialog(null,su.getMessage());
        }
        limpiarEntradas();
        desHabilitar();*/
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        /*String idcaja=txtIdCarrito.getText();
        if(idcaja.equalsIgnoreCase(""))
        JOptionPane.showMessageDialog(null, "INGRESE DATOS CORRECTOS");
        else
        {
            try{
                Caja cajaBuscada = CajaDAO.getInstancia().buscarCaja(idcaja);
                if(cajaBuscada != null)
                {
                    txtImporte.setText(cajaBuscada.getSupermercado().getNombre());

                    supermercadoSelec = cajaBuscada.getSupermercado();

                    txtIdCaja.setText(cajaBuscada.getSupermercado().getIdSupermercado());
                    txtNombrePro.setText(cajaBuscada.getSupermercado().getNombre());
                    txtNCaja.setText(cajaBuscada.getSupermercado().getDireccion());
                    habilitar();
                }
                else
                JOptionPane.showMessageDialog(null, "El ID Caja no existe");
            } catch(SQLException su) {
                JOptionPane.showMessageDialog(null,su.getMessage());
            }
        }*/
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        limpiarEntradas();
        desHabilitar();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCarrito dialog = new DialogCarrito();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionarCaja;
    private javax.swing.JButton btnSeleccionarProdcuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidadComprada;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtFechaH;
    private javax.swing.JTextField txtIdCaja;
    private javax.swing.JTextField txtIdCarrito;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtMedioPago;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNroCaja;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtPuntosAcumulados;
    private javax.swing.JTextField txtPuntosGanados;
    // End of variables declaration//GEN-END:variables
}
