
package presentacion;
import java.awt.Color;
import javax.swing.JPanel;

public class FrmPrincipalSupervisor extends javax.swing.JFrame {

    private static FrmPrincipalSupervisor instancia;

    public static FrmPrincipalSupervisor getInstancia() {
        if(instancia == null){
            instancia = new FrmPrincipalSupervisor();
        }
        return instancia;
    }
    public FrmPrincipalSupervisor() {
        initComponents();
        setLocationRelativeTo(null);
        deshabilitar();
    }
    
    public void setColor(JPanel x){
        x.setBackground(new Color(255, 255, 100));
    }
    
    public void resetColor(JPanel x){
        x.setBackground(new Color(245, 253, 0));
    }
    
    public void deshabilitar() {
        if(Globales.adminGlobal != null) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOperaciones = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCompra = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnProveedor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jPanelProveedor = new javax.swing.JPanel();
        btnAgregarProveedor = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btnBuscarProveedor = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanelCompra = new javax.swing.JPanel();
        btnAgregarCompra = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        btnBuscarCompra = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelOperaciones.setBackground(new java.awt.Color(230, 230, 0));
        jPanelOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("SUPERMARKET");
        jPanelOperaciones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, -1));
        jPanelOperaciones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 10));

        btnCompra.setBackground(new java.awt.Color(247, 247, 0));
        btnCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompraMouseExited(evt);
            }
        });
        btnCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3775748-check-date-list-planner-time_108972.png"))); // NOI18N
        btnCompra.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Compra");
        btnCompra.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanelOperaciones.add(btnCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 60));

        btnProveedor.setBackground(new java.awt.Color(247, 247, 0));
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedorMouseExited(evt);
            }
        });
        btnProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/customer_seller_icon_179551.png"))); // NOI18N
        btnProveedor.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Proveedor");
        btnProveedor.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanelOperaciones.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 60));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("X");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelOperaciones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        getContentPane().add(jPanelOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        jPanelProveedor.setBackground(new java.awt.Color(230, 230, 0));
        jPanelProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelProveedorMouseExited(evt);
            }
        });

        btnAgregarProveedor.setBackground(new java.awt.Color(245, 253, 0));
        btnAgregarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseExited(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setText("AGREGAR PROVEEDOR");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarProveedorLayout = new javax.swing.GroupLayout(btnAgregarProveedor);
        btnAgregarProveedor.setLayout(btnAgregarProveedorLayout);
        btnAgregarProveedorLayout.setHorizontalGroup(
            btnAgregarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(12, 12, 12)
                .addComponent(jLabel41)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnAgregarProveedorLayout.setVerticalGroup(
            btnAgregarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(jLabel47)
        );

        btnBuscarProveedor.setBackground(new java.awt.Color(245, 253, 0));
        btnBuscarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseExited(evt);
            }
        });

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setText("BUSCAR PROVEEDOR");
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBuscarProveedorLayout = new javax.swing.GroupLayout(btnBuscarProveedor);
        btnBuscarProveedor.setLayout(btnBuscarProveedorLayout);
        btnBuscarProveedorLayout.setHorizontalGroup(
            btnBuscarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBuscarProveedorLayout.setVerticalGroup(
            btnBuscarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnBuscarProveedorLayout.createSequentialGroup()
                .addComponent(jLabel48)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProveedorLayout = new javax.swing.GroupLayout(jPanelProveedor);
        jPanelProveedor.setLayout(jPanelProveedorLayout);
        jPanelProveedorLayout.setHorizontalGroup(
            jPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedorLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelProveedorLayout.setVerticalGroup(
            jPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedorLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 270, 80));
        jPanelProveedor.setVisible(false);

        jPanelCompra.setBackground(new java.awt.Color(230, 230, 0));
        jPanelCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCompraMouseExited(evt);
            }
        });

        btnAgregarCompra.setBackground(new java.awt.Color(245, 253, 0));
        btnAgregarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarCompraMouseExited(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setText("AGREGAR COMPRA");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-carrito.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarCompraLayout = new javax.swing.GroupLayout(btnAgregarCompra);
        btnAgregarCompra.setLayout(btnAgregarCompraLayout);
        btnAgregarCompraLayout.setHorizontalGroup(
            btnAgregarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarCompraLayout.setVerticalGroup(
            btnAgregarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnBuscarCompra.setBackground(new java.awt.Color(245, 253, 0));
        btnBuscarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarCompraMouseExited(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setText("BUSCAR COMPRA");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarCompraLayout = new javax.swing.GroupLayout(btnBuscarCompra);
        btnBuscarCompra.setLayout(btnBuscarCompraLayout);
        btnBuscarCompraLayout.setHorizontalGroup(
            btnBuscarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(34, 34, 34))
        );
        btnBuscarCompraLayout.setVerticalGroup(
            btnBuscarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanelCompraLayout = new javax.swing.GroupLayout(jPanelCompra);
        jPanelCompra.setLayout(jPanelCompraLayout);
        jPanelCompraLayout.setHorizontalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompraLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelCompraLayout.setVerticalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, 80));
        jPanelCompra.setVisible(false);

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/238-2385310_super-market-atm-machine-simulator-shopping-mall.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 850, 770));

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseEntered
        setColor(btnProveedor);
        jPanelProveedor.setVisible(true);
    }//GEN-LAST:event_btnProveedorMouseEntered

    private void btnProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMouseExited
        resetColor(btnProveedor);
        jPanelProveedor.setVisible(false);
    }//GEN-LAST:event_btnProveedorMouseExited

    private void btnCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseEntered
        setColor(btnCompra);
        jPanelCompra.setVisible(true);
    }//GEN-LAST:event_btnCompraMouseEntered

    private void btnCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseExited
        resetColor(btnCompra);
        jPanelCompra.setVisible(false);
    }//GEN-LAST:event_btnCompraMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnAgregarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseClicked
        DialogProveedor f = new DialogProveedor();
        f.setVisible(true);
    }//GEN-LAST:event_btnAgregarProveedorMouseClicked

    private void btnAgregarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseEntered
        setColor(btnAgregarProveedor);
        jPanelProveedor.setVisible(true);
    }//GEN-LAST:event_btnAgregarProveedorMouseEntered

    private void btnAgregarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseExited
        resetColor(btnAgregarProveedor);
    }//GEN-LAST:event_btnAgregarProveedorMouseExited

    private void btnBuscarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseClicked
        DialogBuscarProveedor f = new DialogBuscarProveedor();
        f.setVisible(true);
    }//GEN-LAST:event_btnBuscarProveedorMouseClicked

    private void btnBuscarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseEntered
        setColor(btnBuscarProveedor);
        jPanelProveedor.setVisible(true);
    }//GEN-LAST:event_btnBuscarProveedorMouseEntered

    private void btnBuscarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseExited
        resetColor(btnBuscarProveedor);
    }//GEN-LAST:event_btnBuscarProveedorMouseExited

    private void jPanelProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProveedorMouseEntered
        jPanelProveedor.setVisible(true);
    }//GEN-LAST:event_jPanelProveedorMouseEntered

    private void jPanelProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelProveedorMouseExited
        jPanelProveedor.setVisible(false);
    }//GEN-LAST:event_jPanelProveedorMouseExited

    private void btnAgregarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCompraMouseClicked
        DialogCompra f = new DialogCompra();
        f.setVisible(true);
    }//GEN-LAST:event_btnAgregarCompraMouseClicked

    private void btnAgregarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCompraMouseEntered
        setColor(btnAgregarCompra);
        jPanelCompra.setVisible(true);
    }//GEN-LAST:event_btnAgregarCompraMouseEntered

    private void btnAgregarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCompraMouseExited
        resetColor(btnAgregarCompra);
    }//GEN-LAST:event_btnAgregarCompraMouseExited

    private void btnBuscarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCompraMouseClicked
        
    }//GEN-LAST:event_btnBuscarCompraMouseClicked

    private void btnBuscarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCompraMouseEntered
        setColor(btnBuscarCompra);
        jPanelCompra.setVisible(true);
    }//GEN-LAST:event_btnBuscarCompraMouseEntered

    private void btnBuscarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCompraMouseExited
        resetColor(btnBuscarCompra);
    }//GEN-LAST:event_btnBuscarCompraMouseExited

    private void jPanelCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCompraMouseEntered
        jPanelCompra.setVisible(true);
    }//GEN-LAST:event_jPanelCompraMouseEntered

    private void jPanelCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCompraMouseExited
        jPanelCompra.setVisible(false);
    }//GEN-LAST:event_jPanelCompraMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.red);
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel btnAgregarCompra;
    private javax.swing.JPanel btnAgregarProveedor;
    private javax.swing.JPanel btnBuscarCompra;
    private javax.swing.JPanel btnBuscarProveedor;
    private javax.swing.JPanel btnCompra;
    private javax.swing.JPanel btnProveedor;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCompra;
    private javax.swing.JPanel jPanelOperaciones;
    private javax.swing.JPanel jPanelProveedor;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
